Repository Turing-Eras/front_end, pull requests merged in 2021-01, with the labels that each got.

#46 Am form
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Components/App.tsx
  src/Components/FormContainer.tsx
  src/Components/Question.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
Labels: FE, New Feature, UX

#48 Form updates
  .eslintcache
  package-lock.json
  package.json
  src/App.test.tsx
  src/Components/App.tsx
  src/Components/FormContainer.tsx
  src/Components/HeaderComponent.tsx
  src/Components/LoginPage.tsx
  src/Components/Question.tsx
  src/index.tsx
Labels: FE, New Feature

#52 Calender component
  .gitignore
  src/App.test.tsx
  src/Components/App.tsx
  src/Components/CalenderComponent.tsx
  src/Components/FormContainer.tsx
  src/Components/HeaderComponent.tsx
  src/Components/NavBar.tsx
  src/Components/Week.tsx
  src/Styling/Week.css
  src/index.tsx
Labels: FE

#53 Add typescript fix
  package-lock.json
Labels: Bug, FE

#56 Initial testing
  package-lock.json
  package.json
  src/Components/App/App.test.tsx
  src/Components/App/App.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/CalenderComponent.tsx
  src/Components/FormContainer/FormContainer.test.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/HeaderComponent/HeaderComponent.tsx
  src/Components/LoginPage/LoginPage.test.tsx
  src/Components/LoginPage/LoginPage.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Question/Question.test.tsx
  src/Components/Question/Question.tsx
  src/Components/Week.tsx
  src/Components/Week/Week.css
  src/Components/Week/Week.tsx
  src/index.tsx
Labels: FE, Testing

#55 Fix typescript heroku errors
  package.json
Labels: Bug, FE

#58 Progress bar
  package-lock.json
  src/Components/FormContainer/FormContainer.tsx
  src/Components/ProgressBar/ProgressBar.tsx
Labels: FE, New Feature

#61 Get questions
  package-lock.json
  package.json
  src/Components/App/App.test.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/Week/Week.tsx
  src/index.tsx
Labels: FE, New Feature, UX

#64 Testing updates
  package-lock.json
  package.json
  src/Components/CalendarComponent/CalendarComponent.test.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/FormContainer/FormContainer.test.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/HeaderComponent/HeaderComponent.tsx
  src/Components/NavBar/NavBar.test.tsx
  src/Components/ProgressBar/ProgressBar.test.tsx
  src/Components/Week/Week.test.tsx
  src/Components/Week/Week.tsx
Labels: FE, Refactor, Testing

#65 Required form
  .gitignore
  src/Components/App/App.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.tsx
  src/index.tsx
Labels: FE, New Feature

#67 Form query
  src/Components/App/App.tsx
  src/Components/CalendarComponent/CalendarComponent.test.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/Question/Question.test.tsx
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/Week/Week.tsx
Labels: FE, New Feature, Testing

#71 Error handling
  src/Components/App/App.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/Question/Question.test.tsx
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/Week/Week.tsx
Labels: FE

#72 Event form ks
  public/eras-logo-transparent.png
  src/Components/AdditionalQuestions/AdditionalQuestions.css
  src/Components/AdditionalQuestions/AdditionalQuestions.test.tsx
  src/Components/AdditionalQuestions/AdditionalQuestions.tsx
  src/Components/App/App.css
  src/Components/App/App.tsx
  src/Components/CalendarComponent/CalendarComponent.css
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/Event/Event.test.tsx
  src/Components/Event/Event.tsx
  src/Components/EventForm/EventForm.css
  src/Components/EventForm/EventForm.test.tsx
  src/Components/EventForm/EventForm.tsx
  src/Components/FormContainer/FormContainer.css
  src/Components/FormContainer/FormContainer.tsx
  src/Components/FormStartPage/FormStartPage.css
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/HeaderComponent/HeaderComponent.css
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/HeaderComponent/HeaderComponent.tsx
  src/Components/NavBar/NavBar.css
  src/Components/NavBar/NavBar.tsx
  src/Components/ProgressBar/ProgressBar.css
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/Question/Question.css
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.css
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.tsx
  src/Components/Week/Week.css
  src/Components/Week/Week.tsx
Labels: CSS, FE, New Feature, Testing, UI, UX

#75 Design ks
  package-lock.json
  package.json
  public/eras-logo-horizontal.png
  src/Components/AdditionalQuestions/AdditionalQuestions.tsx
  src/Components/App/App.tsx
  src/Components/CalendarComponent/CalendarComponent.css
  src/Components/CalendarComponent/CalendarComponent.test.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/Event/Event.test.tsx
  src/Components/Event/Event.tsx
  src/Components/EventForm/EventForm.tsx
  src/Components/FormStartPage/FormStartPage.css
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/HeaderComponent/HeaderComponent.css
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/HeaderComponent/HeaderComponent.tsx
  src/Components/LoginPage/LoginPage.tsx
  src/Components/NotFound/NotFound.test.tsx
  src/Components/NotFound/NotFound.tsx
  src/Components/Question/Question.css
  src/Components/Question/Question.test.tsx
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.css
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.tsx
  src/Components/Week/Week.css
  src/Components/Week/Week.tsx
Labels: CSS, FE, UI

#73 Edit form mutation
  .eslintcache
  package-lock.json
  package.json
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/Event/Event.test.tsx
  src/Components/Event/Event.tsx
  src/Components/EventForm/EventForm.tsx
  src/Components/Question/Question.test.tsx
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/Week/Week.tsx
Labels: FE, New Feature

#76 Testing
  .gitignore
  src/Components/AdditionalQuestions/AdditionalQuestions.test.tsx
  src/Components/CalendarComponent/CalendarComponent.test.tsx
  src/Components/Event/Event.test.tsx
  src/Components/EventForm/EventForm.test.tsx
  src/Components/FormContainer/FormContainer.test.tsx
  src/Components/FormStartPage/FormStartPage.test.tsx
  src/Components/FormStartPage/FormStartPage.tsx
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/NavBar/NavBar.css
  src/Components/NavBar/NavBar.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Question/Question.test.tsx
  src/Components/RequiredForm/RequiredForm.test.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.test.tsx
  src/Components/TextQuestion/TextQuestion.tsx
  src/Components/Week/Week.test.tsx
  src/Components/Week/Week.tsx
Labels: FE, Testing

#78 Readme
  README.md
Labels: Chore, FE

#82 Todays date
  src/Components/CalendarComponent/CalendarComponent.test.tsx
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/ClickedComponent/ClickedComponent.css
  src/Components/ClickedComponent/ClickedComponent.tsx
  src/Components/Event/Event.tsx
  src/Components/FormContainer/FormContainer.tsx
  src/Components/Question/Question.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.tsx
  src/Components/Week/Week.tsx
Labels: Extension, FE

#83 Event onclick
  src/Components/CalendarComponent/CalendarComponent.tsx
  src/Components/ClickedComponent/ClickedComponent.tsx
Labels: Extension, FE

#85 Am testing updates
  src/Components/HeaderComponent/HeaderComponent.test.tsx
  src/Components/ProgressBar/ProgressBar.test.tsx
  src/Components/RequiredForm/RequiredForm.test.tsx
  src/Components/RequiredForm/RequiredForm.tsx
  src/Components/TextQuestion/TextQuestion.test.tsx
Labels: FE, Testing
